- name: Monitor resource usage on LXC
  hosts: lxc
  become: true
  tasks:
    - name: Ensure lm-sensors is installed
      apt:
        name: lm-sensors
        state: present

    - name: Run sensors-detect non-interactively
      shell: yes | sensors-detect

    - name: Collect resource metrics
      shell: sensors > /tmp/resource_metrics.txt

    - name: Send metrics to InfluxDB
      shell: |
        curl -i -XPOST 'http://{{ influxdb_host }}:8086/write?db=homelab' \
        --data-binary "@/tmp/resource_metrics.txt"
