- name: Redémarrage des conteneurs LXC uniquement
  hosts: all
  become: true
  tasks:
    - name: Redémarrer le conteneur en arrière-plan
      ansible.builtin.shell:
        cmd: nohup reboot &> /dev/null &
      ignore_errors: true  # Ignore les erreurs de déconnexion
      async: 1
      poll: 0

    - name: Attendre que les hôtes soient à nouveau disponibles
      ansible.builtin.wait_for_connection:
        timeout: 120  # Augmentez si nécessaire

    - name: Vérifier que l'hôte est accessible
      ansible.builtin.ping:
