- name: Redémarrage des conteneurs LXC uniquement
  hosts: all
  become: true
  tasks:
    - name: Redémarrer le conteneur avec timeout
      ansible.builtin.shell:
        cmd: timeout 120s reboot

    - name: Attendre 30 secondes pour le redémarrage
      ansible.builtin.pause:
        seconds: 120
