- name: Mise à jour des conteneurs LXC sans reboot
  hosts: all
  become: true
  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
