- name: Redémarrage des conteneurs LXC uniquement
  hosts: all
  become: true
  tasks:
    - name: Redémarrer le conteneur
      ansible.builtin.command:
        cmd: reboot
        timeout: 120  # Délai d'expiration en secondes
