- name: Redémarrage des serveurs
  hosts: all
  become: true

  tasks:
    - name: Vérifier si un redémarrage est requis
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Redémarrer le serveur si nécessaire
      reboot: {}
      when: reboot_required.stat.exists
