- name: Redémarrage forcé des serveurs
  hosts: all
  become: true

  tasks:
    - name: Redémarrer le serveur
      reboot:
        msg: "Redémarrage forcé déclenché via Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        reboot_timeout: 600

