- name: Redémarrage des serveurs
  hosts: all
  become: true

  tasks:
    - name: Vérifier si un redémarrage est requis
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Redémarrer le serveur si nécessaire
      reboot:
        msg: "Redémarrage automatique via Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 30
      when: reboot_required.stat.exists
