- name: Mise à jour des serveurs sans reboot
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour l'index des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      apt:
        upgrade: dist
