- name: Upgrade Proxmox to version 8.4
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Check current Proxmox version
      shell: pveversion
      register: pve_version

    - name: Display current Proxmox version
      debug:
        msg: "Current Proxmox version is: {{ pve_version.stdout }}"
        
    - name: Désactiver temporairement la vérification des signatures APT
      lineinfile:
        path: /etc/apt/apt.conf.d/99norequire
        line: 'APT::Get::AllowUnauthenticated "true";'

    - name: Update all packages
      apt:
        upgrade: dist

    - name: Clean up unused packages
      apt:
        autoclean: yes

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
