- name: Mise à jour des serveurs sans reboot
  hosts: all
  become: true

  tasks:
    - name: Vérifier si le répertoire /etc/apt/apt.conf.d existe
      stat:
        path: /etc/apt/apt.conf.d
      register: apt_conf_dir

    - name: Créer le répertoire /etc/apt/apt.conf.d si nécessaire
      file:
        path: /etc/apt/apt.conf.d
        state: directory
      when: not apt_conf_dir.stat.exists

    - name: Désactiver temporairement la vérification des signatures APT
      copy:
        dest: /etc/apt/apt.conf.d/99norequire
        content: |
          APT::Get::AllowUnauthenticated "true";

    - name: Mettre à jour l'index des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      apt:
        upgrade: dist

    - name: Supprimer la configuration temporaire
      file:
        path: /etc/apt/apt.conf.d/99norequire
        state: absent
