- name: Upgrade Proxmox to version 8.4
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Check current Proxmox version
      shell: pveversion
      register: pve_version

    - name: Display current Proxmox version
      debug:
        msg: "Current Proxmox version is: {{ pve_version.stdout }}"

    - name: Update all packages
      apt:
        upgrade: dist

    - name: Clean up unused packages
      apt:
        autoclean: yes

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
